name: Docker CI

on:
    push:
        branches:
            - main
            - master

    workflow_run:
        workflows: ['build']
        types:
            - completed

    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkoutcode
              uses: actions/checkout@v2

            - name: Login to DockerHub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build and push Docker image
              uses: docker/build-push-actions@v1
              with:
                  context: .
                  push: true
                  tags: melimelo44/workflow_test:latest
